Initial PR for
vinaygopinath/ngMeta pull request #19
Opened 2016-09-27 22:40 UTC by martyzz1

Please Review, haven't been able to test this with ngRoute. only ui-router. 

Based on some feedback from the ui-router team here 
https://github.com/angular-ui/ui-router/issues/3045

This would help resolve #14

2016-09-30 07:35 UTC, vinaygopinath requested changes
Hey,

Thank you so much for offering to implement this feature, getting in touch with the ui-router folks and getting it done! Except for a few minor suggestions, I think the code looks good, and I'd be happy to put it through some tests, merge and release a new version.

2016-09-30 07:35 UTC, vinaygopinath commented on src/ngMeta.js
> +          if (current.meta) {
Isn't this if-else chain equivalent to 

``` javascript
readRouteMeta(angular.copy(current.meta || current.data.meta));
```

2016-09-30 07:35 UTC, vinaygopinath commented on README.md
> +**N.B. if you wish to take advantage of ui-router's nested views and data inheritence, then you should specify your "meta" config underneath the "data" property like this**
Would you mind moving this to a separate section after the "Dynamic meta tags" section? I wouldn't want to intimidate newcomers trying to set up ngMeta with anything more than the basic configuration needed to get up and running.

Also, given that it's backwards-compatible, I believe it's safe to move all the examples to use

``` javascript
data: {
  meta: {

  }
}
```

(I can deal with this after your PR is merged)

2016-09-30 07:35 UTC, vinaygopinath commented on src/ngMeta.js
> +        var mergedMeta = angular.merge({}, parentMetaData, originalData.meta);
Shouldn't this statement be in the if block below? Calling angular.merge when both `parentMetaData` and `originalData.meta` are null/undefined wouldn't serve a purpose anyway.

2016-09-30 08:36 UTC, martyzz1 commented
hey no worries, thanks for the feedback... Done I believe

2016-10-01 09:35 UTC, vinaygopinath approved these changes

2016-10-01 09:36 UTC, merged